/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Person;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Yutong Zhen
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    Person person;
    public CreatePanel(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPanel = new javax.swing.JPanel();
        btnDemographic = new javax.swing.JButton();
        btnAddress = new javax.swing.JButton();
        btnBank = new javax.swing.JButton();
        btnDriver = new javax.swing.JButton();
        btnMedical = new javax.swing.JButton();
        AddressPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtZipCode = new javax.swing.JTextField();
        btnSaveAddress = new javax.swing.JButton();
        BankPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBankName = new javax.swing.JTextField();
        txtRoutingNum = new javax.swing.JTextField();
        txtAccountNum = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        btnSaveBank = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtAccountType = new javax.swing.JTextField();
        DemographicPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtPhoneNum = new javax.swing.JTextField();
        txtBirthday = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        btnSaveDemographic = new javax.swing.JButton();
        DriverPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        txtIssuedDate = new javax.swing.JTextField();
        txtExpirationDate = new javax.swing.JTextField();
        txtBloodType = new javax.swing.JTextField();
        btnSaveDriver = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        MedicalPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtRecordNum = new javax.swing.JTextField();
        txtAlergy1 = new javax.swing.JTextField();
        txtAlergy2 = new javax.swing.JTextField();
        txtAlergy3 = new javax.swing.JTextField();
        btnSaveMedical = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        btnDemographic.setText("Create Demographic Information");
        btnDemographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemographicActionPerformed(evt);
            }
        });

        btnAddress.setText("Create Address Information");
        btnAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddressActionPerformed(evt);
            }
        });

        btnBank.setText("Create Bank Account Information");
        btnBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBankActionPerformed(evt);
            }
        });

        btnDriver.setText("Create Driver's license Information");
        btnDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDriverActionPerformed(evt);
            }
        });

        btnMedical.setText("Create Medical Record Information");
        btnMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPanelLayout = new javax.swing.GroupLayout(btnPanel);
        btnPanel.setLayout(btnPanelLayout);
        btnPanelLayout.setHorizontalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnDemographic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDriver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMedical, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBank, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        btnPanelLayout.setVerticalGroup(
            btnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnDemographic)
                .addGap(18, 18, 18)
                .addComponent(btnAddress)
                .addGap(18, 18, 18)
                .addComponent(btnBank)
                .addGap(18, 18, 18)
                .addComponent(btnDriver)
                .addGap(18, 18, 18)
                .addComponent(btnMedical)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        add(btnPanel, "card4");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Create Address Information");

        jLabel2.setText("Street:");

        jLabel3.setText("City:");

        jLabel4.setText("State:");

        jLabel5.setText("Zip Code:");

        btnSaveAddress.setText("Save");
        btnSaveAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddressPanelLayout = new javax.swing.GroupLayout(AddressPanel);
        AddressPanel.setLayout(AddressPanelLayout);
        AddressPanelLayout.setHorizontalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddressPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(AddressPanelLayout.createSequentialGroup()
                                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(txtCity)
                                    .addComponent(txtState)
                                    .addComponent(txtZipCode)))))
                    .addGroup(AddressPanelLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnSaveAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(308, Short.MAX_VALUE))
        );
        AddressPanelLayout.setVerticalGroup(
            AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveAddress)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        add(AddressPanel, "card2");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Create Bank Account Information");

        jLabel7.setText("Bank Name:");

        jLabel8.setText("Routing Number:");

        jLabel9.setText("Account Number:");

        jLabel10.setText("Account Balance:");

        txtBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBalanceActionPerformed(evt);
            }
        });

        btnSaveBank.setText("Save");
        btnSaveBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveBankActionPerformed(evt);
            }
        });

        jLabel11.setText("Account Type:");

        javax.swing.GroupLayout BankPanelLayout = new javax.swing.GroupLayout(BankPanel);
        BankPanel.setLayout(BankPanelLayout);
        BankPanelLayout.setHorizontalGroup(
            BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankPanelLayout.createSequentialGroup()
                .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BankPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(BankPanelLayout.createSequentialGroup()
                                .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBankName, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(txtRoutingNum)
                                    .addComponent(txtAccountNum)
                                    .addComponent(txtBalance)
                                    .addComponent(txtAccountType)))))
                    .addGroup(BankPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(btnSaveBank, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        BankPanelLayout.setVerticalGroup(
            BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BankPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtRoutingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtAccountNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveBank)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        add(BankPanel, "card3");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel12.setText("Create Demographic Information");

        jLabel13.setText("First Name:");

        jLabel14.setText("Last Name:");

        jLabel15.setText("Phone Number:");

        jLabel16.setText("Birthday:");

        jLabel17.setText("Age:");

        jLabel18.setText("Height:");

        jLabel19.setText("Weight:");

        jLabel20.setText("SSN：");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        btnSaveDemographic.setText("Save");
        btnSaveDemographic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDemographicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DemographicPanelLayout = new javax.swing.GroupLayout(DemographicPanel);
        DemographicPanel.setLayout(DemographicPanelLayout);
        DemographicPanelLayout.setHorizontalGroup(
            DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemographicPanelLayout.createSequentialGroup()
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DemographicPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(DemographicPanelLayout.createSequentialGroup()
                                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstName)
                                    .addComponent(txtLastName)
                                    .addComponent(txtPhoneNum)
                                    .addComponent(txtBirthday)
                                    .addComponent(txtAge)
                                    .addComponent(txtHeight)
                                    .addComponent(txtWeight)
                                    .addComponent(txtSSN, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)))))
                    .addGroup(DemographicPanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnSaveDemographic, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        DemographicPanelLayout.setVerticalGroup(
            DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemographicPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DemographicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveDemographic)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(DemographicPanel, "card5");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel21.setText("Create Drive License Information");

        jLabel22.setText("License Number:");

        jLabel23.setText("Issued Date:");

        jLabel24.setText("Expiration Date:");

        jLabel25.setText("Blood Type:");

        btnSaveDriver.setText("Save");
        btnSaveDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDriverActionPerformed(evt);
            }
        });

        jLabel26.setText("Picture:");

        btnUpload.setText("Upload");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DriverPanelLayout = new javax.swing.GroupLayout(DriverPanel);
        DriverPanel.setLayout(DriverPanelLayout);
        DriverPanelLayout.setHorizontalGroup(
            DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriverPanelLayout.createSequentialGroup()
                .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DriverPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(DriverPanelLayout.createSequentialGroup()
                                .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(txtIssuedDate)
                                    .addComponent(txtExpirationDate)
                                    .addComponent(txtBloodType)
                                    .addComponent(btnUpload)))))
                    .addGroup(DriverPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(btnSaveDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        DriverPanelLayout.setVerticalGroup(
            DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtIssuedDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DriverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(btnUpload))
                .addGap(18, 18, 18)
                .addComponent(btnSaveDriver)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        add(DriverPanel, "card6");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel27.setText("Create Medical Information");

        jLabel28.setText("Record Number:");

        jLabel29.setText("Alergy1:");

        jLabel30.setText("Alergy2:");

        jLabel31.setText("Alergy3:");

        btnSaveMedical.setText("Save");
        btnSaveMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMedicalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MedicalPanelLayout = new javax.swing.GroupLayout(MedicalPanel);
        MedicalPanel.setLayout(MedicalPanelLayout);
        MedicalPanelLayout.setHorizontalGroup(
            MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalPanelLayout.createSequentialGroup()
                .addGroup(MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MedicalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(MedicalPanelLayout.createSequentialGroup()
                                .addGroup(MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel31))
                                .addGap(18, 18, 18)
                                .addGroup(MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRecordNum, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(txtAlergy1)
                                    .addComponent(txtAlergy2)
                                    .addComponent(txtAlergy3)))))
                    .addGroup(MedicalPanelLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnSaveMedical, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        MedicalPanelLayout.setVerticalGroup(
            MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MedicalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSaveMedical)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        add(MedicalPanel, "card7");
    }// </editor-fold>//GEN-END:initComponents

    private void txtBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBalanceActionPerformed

    private void btnAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddressActionPerformed
        // TODO add your handling code here:
        DemographicPanel.setVisible(false);
        AddressPanel.setVisible(true);
        BankPanel.setVisible(false);
        DriverPanel.setVisible(false);
        MedicalPanel.setVisible(false);
        btnPanel.setVisible(false);
    }//GEN-LAST:event_btnAddressActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void btnDemographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemographicActionPerformed
        // TODO add your handling code here:
        DemographicPanel.setVisible(true);
        AddressPanel.setVisible(false);
        BankPanel.setVisible(false);
        DriverPanel.setVisible(false);
        MedicalPanel.setVisible(false);
        btnPanel.setVisible(false);
    }//GEN-LAST:event_btnDemographicActionPerformed

    private void btnBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankActionPerformed
        // TODO add your handling code here:
        DemographicPanel.setVisible(false);
        AddressPanel.setVisible(false);
        BankPanel.setVisible(true);
        DriverPanel.setVisible(false);
        MedicalPanel.setVisible(false);
        btnPanel.setVisible(false);
    }//GEN-LAST:event_btnBankActionPerformed

    private void btnDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDriverActionPerformed
        // TODO add your handling code here:
        DemographicPanel.setVisible(false);
        AddressPanel.setVisible(false);
        BankPanel.setVisible(false);
        DriverPanel.setVisible(true);
        MedicalPanel.setVisible(false);
        btnPanel.setVisible(false);
    }//GEN-LAST:event_btnDriverActionPerformed

    private void btnMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicalActionPerformed
        // TODO add your handling code here:
        btnPanel.setVisible(false);
        DemographicPanel.setVisible(false);
        AddressPanel.setVisible(false);
        BankPanel.setVisible(false);
        DriverPanel.setVisible(false);
        MedicalPanel.setVisible(true);
    }//GEN-LAST:event_btnMedicalActionPerformed

    private void btnSaveAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAddressActionPerformed
        // TODO add your handling code here:
        person.address.setStreet(txtStreet.getText());
        person.address.setCity(txtCity.getText());
        person.address.setState(txtState.getText());
        person.address.setZipcode(txtZipCode.getText());
        JOptionPane.showMessageDialog(null, "Save successfully");
        
    }//GEN-LAST:event_btnSaveAddressActionPerformed

    private void btnSaveDemographicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDemographicActionPerformed
        // TODO add your handling code here:\
        person.setFirstName(txtFirstName.getText());
        person.setLastName(txtLastName.getText());
        person.setAge(txtAge.getText());
        person.setBirthday(txtBirthday.getText());
        person.setHeight(txtHeight.getText());
        person.setWeight(txtWeight.getText());
        person.setPhoneNum(txtPhoneNum.getText());
        person.setSSN(txtSSN.getText());
        JOptionPane.showMessageDialog(null, "Save successfully");
        
    }//GEN-LAST:event_btnSaveDemographicActionPerformed

    private void btnSaveDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDriverActionPerformed
        // TODO add your handling code here:
        person.driverLicense.setLicenseNum(txtLicenseNum.getText());
        person.driverLicense.setDateIssued(txtIssuedDate.getText());
        person.driverLicense.setDateExpiration(txtExpirationDate.getText());
        person.driverLicense.setBloodType(txtBloodType.getText());
        JOptionPane.showMessageDialog(null, "Save successfully");
    }//GEN-LAST:event_btnSaveDriverActionPerformed

    private void btnSaveMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMedicalActionPerformed
        // TODO add your handling code here:
        person.medicalRecord.setRecordNum(txtRecordNum.getText());
        person.medicalRecord.setAlergy1(txtAlergy1.getText());
        person.medicalRecord.setAlergy2(txtAlergy2.getText());
        person.medicalRecord.setAlergy3(txtAlergy3.getText());
        JOptionPane.showMessageDialog(null, "Save successfully");
    }//GEN-LAST:event_btnSaveMedicalActionPerformed

    private void btnSaveBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveBankActionPerformed
        // TODO add your handling code here:
        if((txtAccountType.getText().equals("Saving")  || txtAccountType.getText().equals("saving"))==true){
            person.savingAccount.setAccountNum(txtAccountNum.getText());
            person.savingAccount.setBankName(txtBankName.getText());
            person.savingAccount.setRouteNum(txtRoutingNum.getText());
            person.savingAccount.setBalance(txtBalance.getText());
        }
        if((txtAccountType.getText().equals("Checking") || txtAccountType.getText().equals("checking"))==true){
            person.checkingAccount.setAccountNum(txtAccountNum.getText());
            person.checkingAccount.setBankName(txtBankName.getText());
            person.checkingAccount.setRouteNum(txtRoutingNum.getText());
            person.checkingAccount.setBalance(txtBalance.getText());
        }
        JOptionPane.showMessageDialog(null, "Save successfully");
        
    }//GEN-LAST:event_btnSaveBankActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        addPicture(btnUpload);
    }//GEN-LAST:event_btnUploadActionPerformed

    public static void addPicture(JButton button) {
         JFileChooser chooser = new JFileChooser();
		  chooser.setMultiSelectionEnabled(true);
		  /** Choose the type of file. * */
		  FileNameExtensionFilter filter = new FileNameExtensionFilter("jpg","png");
		  chooser.setFileFilter(filter);
		  int returnVal = chooser.showOpenDialog(button);
		  if (returnVal == JFileChooser.APPROVE_OPTION) { 
		   /** Get the slected file* */
		   File[] arrfiles = chooser.getSelectedFiles();
		   if (arrfiles == null || arrfiles.length == 0) {
		    return;
		   } 
                    //To confirm the type of upload file is .jpg or .png
                    File  ff = chooser.getSelectedFile();
                    String fileName =ff.getName();
                    String prefix=fileName.substring(fileName.lastIndexOf(".")+1);
                    if(!(prefix.equals("jpg") || prefix.equals("png"))){
		 JOptionPane.showMessageDialog(new JDialog(),":Choose jpg or png type file");
		 return;
		 }
                   FileInputStream input = null;
		   FileOutputStream out = null;
                   String path = "F:\\INFO5100\\Assignment1\\Picture";
                   try {
		    for (File f : arrfiles) {
		     File dir = new File(path);
                     
		     File[] fs = dir.listFiles();
		     HashSet<String> set = new HashSet<String>();
		     for (File file : fs) {
		      set.add(file.getName());
		     }
		     
		     String absolutePath = chooser.getSelectedFile().getAbsolutePath();
		     ImageIcon imageIcon = new ImageIcon(absolutePath);
		     input = new FileInputStream(f);
		     byte[] buffer = new byte[1024];
		     File des = new File(path, "0.jpg");
		     out = new FileOutputStream(des);
		     int len = 0;
		     while (-1 != (len = input.read(buffer))) {
		      out.write(buffer, 0, len);
		     }
		     out.close();
		     input.close();
		    }
		    JOptionPane.showMessageDialog(null, "Upload Successfully！", "Tips",
		      JOptionPane.INFORMATION_MESSAGE);
		   } catch (FileNotFoundException e1) {
		    JOptionPane.showMessageDialog(null, "Upload failed！", "Tips",
		      JOptionPane.ERROR_MESSAGE);
		    e1.printStackTrace();
		   } catch (IOException e1) {
		    JOptionPane.showMessageDialog(null, "Upload failed！", "Tips",
		      JOptionPane.ERROR_MESSAGE);
		    e1.printStackTrace();
		   }
              
        
    }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddressPanel;
    private javax.swing.JPanel BankPanel;
    private javax.swing.JPanel DemographicPanel;
    private javax.swing.JPanel DriverPanel;
    private javax.swing.JPanel MedicalPanel;
    private javax.swing.JButton btnAddress;
    private javax.swing.JButton btnBank;
    private javax.swing.JButton btnDemographic;
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnMedical;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JButton btnSaveAddress;
    private javax.swing.JButton btnSaveBank;
    private javax.swing.JButton btnSaveDemographic;
    private javax.swing.JButton btnSaveDriver;
    private javax.swing.JButton btnSaveMedical;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAccountNum;
    private javax.swing.JTextField txtAccountType;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtAlergy1;
    private javax.swing.JTextField txtAlergy2;
    private javax.swing.JTextField txtAlergy3;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtBloodType;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtExpirationDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIssuedDate;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNum;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtRecordNum;
    private javax.swing.JTextField txtRoutingNum;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtWeight;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
