

package userinterface.RestaurantAdminRole;


import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Order.OrderDirectory;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    /** Creates new form AdminWorkAreaJPanel */
    private JPanel userProcessContainer;
    private RestaurantDirectory restaurantDirectory;
    private EcoSystem system;
    private OrderDirectory orderDirectory;
    private UserAccount account;
    private DeliveryManDirectory deliveryManDirectory;
    
    public AdminWorkAreaJPanel(JPanel userProcessContainer,UserAccount account, EcoSystem system, RestaurantDirectory restaurantDirectory,DeliveryManDirectory deliveryManDirectory, OrderDirectory orderDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.restaurantDirectory = restaurantDirectory;
        this.system = system;
        this.orderDirectory = orderDirectory;
        this.account = account;
        this.deliveryManDirectory = deliveryManDirectory;
      
        //valueLabel.setText();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ManageInfoBtn = new javax.swing.JButton();
        manageMenuBtn = new javax.swing.JButton();
        manageOrdersBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Restaurant -Adminstrator WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        ManageInfoBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        ManageInfoBtn.setText("Manage Restaurant Info");
        ManageInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageInfoBtnActionPerformed(evt);
            }
        });
        add(ManageInfoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 250, -1));

        manageMenuBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        manageMenuBtn.setText("Manage menu");
        manageMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageMenuBtnActionPerformed(evt);
            }
        });
        add(manageMenuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 250, -1));

        manageOrdersBtn.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        manageOrdersBtn.setText("Manage Orders");
        manageOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrdersBtnActionPerformed(evt);
            }
        });
        add(manageOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 250, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Business/Picture/restaurantAdminArea.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 260, 220));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageInfoBtnActionPerformed
        // TODO add your handling code here:
        ManageResturantInfoJPanel manageResturantInfoJPanel = new ManageResturantInfoJPanel(userProcessContainer,account, system, restaurantDirectory);
        userProcessContainer.add("manageResturantInfoJPanel",manageResturantInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_ManageInfoBtnActionPerformed

    private void manageMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageMenuBtnActionPerformed
        ManageMenuJPanel manageMenuJPanel = new ManageMenuJPanel(userProcessContainer,account, system, restaurantDirectory);
        userProcessContainer.add("manageMenuJPanel",manageMenuJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageMenuBtnActionPerformed

    private void manageOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrdersBtnActionPerformed
        ManageRestaurantOrderJPanel manageResturantInfoJPanel = new ManageRestaurantOrderJPanel(userProcessContainer,account, system, restaurantDirectory,deliveryManDirectory,orderDirectory);
        userProcessContainer.add("manageResturantInfoJPanel",manageResturantInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrdersBtnActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageInfoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton manageMenuBtn;
    private javax.swing.JButton manageOrdersBtn;
    // End of variables declaration//GEN-END:variables
    
}
